[[constraint]]
  name = "github.com/NYTimes/gizmo"
  version = "0.4.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Pallinder/go-randomdata"
  version = "1.1.0"
