---
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    env: poc

scrape_configs:
  - job_name: prometheus
    honor_labels: true

    static_configs:
      - targets: ['localhost:9090']
        labels:
          language: go
          service: prometheus

  - job_name: worker
    honor_labels: true

    static_configs:
      - targets: ['app:8080']
        labels:
          language: go
          service: worker
